### ISSUE TITLE
CUDA Out of Memory

### ISSUE THREAD

**Issue by aniketde** [salesforce/ALBEF#6]
While fine-tuning the network on larger dataset (on 8 A100 GPUs) for text to image retrieval, I always face the issue of CUDA OUT OF MEMORY,  after running for 1000-1500 batches. If the batch size is reduced to 16 (from 32), this issue is faced after 2500-3000 batches. 

I am currently using - 
- pytorch 1.8.0
- transformers 4.8.1
- timm 0.4.9
- batch_size_train: 32
- batch_size_test: 32
E.g.: 
RuntimeError: CUDA out of memory. Tried to allocate 194.00 MiB (GPU 5; 39.59 GiB total capacity; 34.18 GiB already allocated;111.19 MiB free; 37.37 GiB reserved in total by PyTorch).

Did you face any of these issues during fine-tuning?

**Comment by aniketde** [comment]
Issue is resolved. Length of the captions was long and if there non-English language caption involved it throws the error.

**Comment by tarunn2799** [comment]
Hi @aniketde, is there a particular limit on the length of the caption or is there somehow I can increase the acceptable length within the BERT config?

What did you manage to do about the non-english language captions?

**Comment by paganpasta** [comment]
@tarunn2799 @aniketde @LiJunnan1992 

For this issue and #11 , I found that Line [99](https://github.com/salesforce/ALBEF/blob/6224e78e5292757ca9c7d5add3e415010955a58b/Retrieval.py#L90)

> text_input = tokenizer(text, padding='longest', max_length=30, return_tensors="pt").to(device)

produced variable length text_input larger than max_length=30. I believe **truncation** is the key here. Replacing the line with 

> text_input = tokenizer(text, padding='max_length', truncation=True, max_length=30, return_tensors="pt").to(device)

fixed the OOM issue.

Regarding non-english characters, I did not find any problem while using the approach with a mix of Chinese and English characters in the captions.
